server:
    applicationConnectors:
        - type: http
          port: 8080
          bindHost: localhost
logging:
    loggers:
          org.hibernate.SQL: ALL
    appenders:
        - type: console
          threshold: DEBUG
          target: stdout
        - type: file
          currentLogFilename: logs/dropwizardtest.log
          archivedLogFilenamePattern: logs/dropwizardtest-%d.log.gz
          archivedFileCount: 5
          threshold: ALL
          timeZone: UTC
